/*
ExoGridChart Rust SDK
Safe wrapper around C FFI

Usage:
    use exogrid::{Client, Exchanges};

    let mut client = Client::init()?;
    client.start(Exchanges::All, |tick| {
        println!("${:.2} x {:.8}", tick.price, tick.size);
    })?;
    std::thread::sleep(std::time::Duration::from_secs(10));
    client.stop();
*/

use std::sync::{Arc, Mutex};
use std::ffi::CStr;

// C FFI declarations (would normally be generated by bindgen)
extern "C" {
    fn exo_init() -> i32;
    fn exo_deinit();
    fn exo_is_initialized() -> bool;
    fn exo_start(exchanges: u32, callback: extern "C" fn(*const Tick)) -> i32;
    fn exo_stop();
    fn exo_get_tick_count() -> u64;
    fn exo_get_matrix_stats(ticker_id: u8) -> MatrixStats;
}

#[repr(C)]
pub struct Tick {
    pub price: f32,
    pub size: f32,
    pub side: u8,
    pub timestamp_ns: u64,
    pub exchange_id: u32,
    pub ticker_id: u8,
}

#[repr(C)]
pub struct MatrixStats {
    pub ticks_processed: u64,
    pub total_volume: u64,
    pub exchange_ticks: [u64; 3],
}

pub type TickCallback = Arc<Mutex<dyn Fn(&Tick) + Send>>;

#[derive(Debug, Clone, Copy)]
pub enum Exchanges {
    Coinbase = 0x1,
    Kraken = 0x2,
    LCX = 0x4,
    All = 0x7,
}

impl Exchanges {
    pub fn bits(self) -> u32 {
        self as u32
    }
}

pub struct Client {
    initialized: bool,
    started: bool,
}

impl Client {
    /// Initialize SDK
    pub fn init() -> Result<Self, String> {
        unsafe {
            if exo_init() != 0 {
                return Err("Failed to initialize ExoGrid".to_string());
            }
        }
        Ok(Client {
            initialized: true,
            started: false,
        })
    }

    /// Start streaming
    pub fn start<F>(&mut self, exchanges: Exchanges, callback: F) -> Result<(), String>
    where
        F: Fn(&Tick) + Send + 'static,
    {
        if self.started {
            return Err("Already started".to_string());
        }

        unsafe {
            let result = exo_start(
                exchanges.bits(),
                |tick: *const Tick| {
                    if !tick.is_null() {
                        callback(unsafe { &*tick });
                    }
                },
            );

            if result != 0 {
                return Err("Failed to start streaming".to_string());
            }
        }

        self.started = true;
        Ok(())
    }

    /// Stop streaming
    pub fn stop(&mut self) {
        if self.started {
            unsafe {
                exo_stop();
            }
            self.started = false;
        }
    }

    /// Get total ticks
    pub fn tick_count(&self) -> u64 {
        unsafe { exo_get_tick_count() }
    }

    /// Get matrix statistics
    pub fn matrix_stats(&self, ticker_id: u8) -> MatrixStats {
        unsafe { exo_get_matrix_stats(ticker_id) }
    }

    /// Check if initialized
    pub fn is_initialized(&self) -> bool {
        self.initialized
    }
}

impl Drop for Client {
    fn drop(&mut self) {
        self.stop();
        unsafe {
            exo_deinit();
        }
    }
}

pub const TICKER_BTC: u8 = 0;
pub const TICKER_ETH: u8 = 1;
pub const TICKER_XRP: u8 = 2;
pub const TICKER_LTC: u8 = 3;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_init() {
        let client = Client::init();
        assert!(client.is_ok());
    }
}
